EmptyApp/Models/Group.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EmptyApp.Models
{
    public class Group : Unit
    {
        //public int Id { get; set; }

        public string Name { get; set; }

        public int? CourseId { get; set; }

        public Course? Course { get; set; }

        public List<Student> Students { get; set; } //=new List<Student>(); - нащо воно потрібно?
    }
}

EmptyApp/Controllers/CourseController.cs
using EmptyApp.Migrations;
using EmptyApp.Models;
using EmptyApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Xml.Linq;

namespace EmptyApp.Controllers
{
    public class CourseController:Controller
    {
        private readonly ICourseService _courseService;

        public CourseController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        public async Task<IActionResult> IndexAsync()
        {
            List<Course> courseList = await _courseService.GetAllAsync();

            return View(courseList);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task <RedirectResult> AddAsync (Course course)
        {
             await _courseService.AddAsync(course);            

            return Redirect("/Course/Index");
        }

        public async Task <RedirectResult> DeleteAsync (int id)
        {
             await _courseService.DeleteAsync(id);            

            return Redirect("/Course/Index");
        }

        [HttpGet]
        public async Task <IActionResult> UpdateAsync(int id)
        {
            Course courseToUpdate = await _courseService.GetOneAsync(id);

            return View(courseToUpdate);
        }

        [HttpPost]
        public async Task<RedirectResult> UpdateAsync(Course course)
        {            
            await _courseService.UpdateAsync(course);           

            return Redirect("/Course/Index");
        }
    }
}

EmptyApp/Controllers/GroupController.cs
using EmptyApp.Models;
using EmptyApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace EmptyApp.Controllers
{
    public class GroupController : Controller
    {       
        private readonly IGroupService _groupService;

         public GroupController(IGroupService groupService)
        {
            _groupService = groupService;
        }

        public async Task <IActionResult> Index(Course course)
        {
            ViewBag.courseId = course.Id;

            var groupList = await _groupService.GetByCourseIdAsync(course.Id);

            return View(groupList);
        }

        [HttpGet]
        public IActionResult Add(int courseId)
        {
            ViewBag.courseId = courseId;
            return View(courseId);
        }

        [HttpPost]
        public async Task <RedirectResult> Add(Group group)
        {
            await _groupService.AddAsync(group);

            return Redirect($"/Group/Index/?id={group.CourseId}");
        }

        [HttpGet]
        public async Task <IActionResult> UpdateAsync(int id) 
        {
            Group groupToUpdate= await _groupService.GetOneAsync(id);

            return View(groupToUpdate);
        }

        [HttpPost]
        public async Task <RedirectResult> UpdateAsync(Group group)
        {
            await _groupService.UpdateAsync(group);

            return Redirect($"/Group/Index/?id={group.CourseId}");
        }

        public async Task <RedirectResult> Delete (int id)
        {
            Group group = await _groupService.GetOneAsync(id);
            
            await _groupService.DeleteAsync(group.Id);

            return Redirect($"/Group/Index/?id={group.CourseId}");
        }
        
    }
}

EmptyApp/Controllers/StudentController.cs
using EmptyApp.Models;
using EmptyApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace EmptyApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        private readonly IGroupService _groupService;
        

        public StudentController(IStudentService studentService)
        {
            _studentService = studentService;
        }

        public async Task <IActionResult> IndexAsync(int groupId)
        {            
            ViewBag.groupId = groupId;

            List<Student> students= await _studentService.GetByGroupIdAsync(groupId);

            return View(students);
        }

        [HttpGet]
        public IActionResult Add(int groupId)
        {
            ViewBag.groupId = groupId;

            return View();
        }

        [HttpPost]
        public async Task <RedirectResult> Add(Student student)
        {
            await _studentService.AddAsync(student);

            return Redirect($"/Student/Index/?groupId={student.GroupId}");
        }
 

        [HttpGet]
        public async Task <IActionResult> UpdateAsync(int id)
        {
            Student student = await _studentService.GetOneAsync(id);

            return View(student);
        }

        [HttpPost]
        public async Task <RedirectResult> UpdateAsync(Student student)
        {
            await _studentService.UpdateAsync(student);

            return Redirect($"/Student/Index/?groupId={student.GroupId}");
        }

        public async Task <RedirectResult> Delete (int id)
        {
            Student student = await _studentService.GetOneAsync(id);

            await _studentService.DeleteAsync(student.Id);

            return Redirect($"/Student/Index/?groupId={student.GroupId}");
        }

        public async Task<RedirectResult> GetCourseIdByGroup(int groupId)
        {
            int? courseId = await _studentService.GetCourseIdByGroupAsync(groupId);

            return Redirect($"/Group/Index/?id={courseId}");
        }
    }
}

EmptyApp/Views/Group/Add.cshtml
@using EmptyApp.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers



<form method='post' >
    <label>Назва Групи:</label><br />
    <input name='name' /><br />

    <label>ID курсу: </label><br />
    <input name='courseId' value='@ViewBag.courseId'/><br />
    

    <input type='submit' value='Send'  />
</form>

EmptyApp/Views/Group/Index.cshtml
@using EmptyApp.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model List<Group>

    <h2>Groups</h2>
    <h4>Count: @Model.Count</h4>

    @foreach(Group group in Model)
    {
        <li title="@group.Name">
           
           <a asp-controller="Student" asp-action="Index" asp-route-groupId="@group.Id">@group.Name ID @group.Id </a><br>
           <a asp-controller="Group" asp-action="Delete" asp-route-id="@group.Id" >Видалити</a>
           <a asp-controller="Group" asp-action="Update" asp-route-id="@group.Id">Змінити</a> <br>
           <br><br>

        </li> 
    }
</ul>

<br>
<a asp-controller="Group" asp-action="Add" asp-route-courseId="@ViewBag.courseId">Додати групу</a>
<a asp-controller="Course" asp-action="Index">Повернутися до курсів</a>

EmptyApp/Views/Group/Update.cshtml
@using EmptyApp.Models;
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@model Group
@{
    string name = Model.Name;
    int? courseId = Model.CourseId;
}

<title>Зміна групи</title>

<h4>Зміна групи "@name"</h4>


<form method='post'>
    <label>Назва групи:</label><br />
    <input name='name' value="@name" /> <br />

    <label> ID курсу: </label><br/>
    <input type='text' name='courseId' value="@courseId" /> <br />

    <input type='submit' value='Send' />
</form>